### ISSUE TITLE
Volatile was removed

### ISSUE THREAD

**Issue by patricio-astudillo** [inferno-pytorch/inferno#125]
https://github.com/inferno-pytorch/inferno/blob/17e7262d98f88c9243e5e29531166d3af3430d4e/inferno/trainers/basic.py#L1050

 UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.

**Comment by constantinpape** [comment]
We are aware of this and working on a Pull Request #117 that will introduce `torch.no_grad()` in the appropriate places.
Note that our current policy is to support both pytorch 0.3 and 0.4 until 1.0 is released.
This means we will keep both `volatile` and `torch.no_grad()` at the expense of having the `UserWarning` in 0.4.

**Comment by nasimrahaman** [comment]
@patricio-astudillo the warning is supressed in master. :+1:
