### ISSUE TITLE
RandomScaleSegmentation twice in transform/image.py

### ISSUE THREAD

**Issue by Ynzl** [inferno-pytorch/inferno#131]
code for class RandomScaleSegmentation duplicated.
it's identical except for the padding mode (and empty lines)

https://github.com/inferno-pytorch/inferno/blob/c83f2ec15a512a40239dcec169633eab26de8b77/inferno/io/transform/image.py#L86

https://github.com/inferno-pytorch/inferno/blob/c83f2ec15a512a40239dcec169633eab26de8b77/inferno/io/transform/image.py#L644

**Comment by constantinpape** [comment]
Thanks for noticing, this looks like some merge gone wrong.
I will remove the version with weird spaces.
And I think `constant` padding is appropriate here, which is in line with the name of the `pad_const` argument.

**Comment by constantinpape** [comment]
Fixed in  e6fa330
