### ISSUE TITLE
Clean up `extensions/layers`

### ISSUE THREAD

**Issue by constantinpape** [inferno-pytorch/inferno#140]
We currently have a bunch of files in `extensions/layers` that implement somewhat redundant functionality:
- `building_blocks`: Implements residual block in `ResBlockBase` and `ResBlock`
- `prefab`: Implements residual block in `ResidualBlock`
- `res_unet`: Implements residual u-net.
- `unet_base`: Implements u-net base class.

I would vote to merge `building_blocks` and `prefab` and if possible also merge the residual block implementations in there. I like @DerThorsten suggestions to name the new file `conv_blocks`,
because this makes clear what's in there. 

Regarding the unet:
Maybe put everything into a single `unet` file?

**Comment by nasimrahaman** [comment]
One way would be to create a `.../extentions/zoo` where the model definitions live. It could function as an extention to `torchvision.models`, and we might eventually consider using the torchvision API to include pretrained models.

**Comment by constantinpape** [comment]
See pull request #144.

**Comment by nasimrahaman** [comment]
This appears to be fixed.
