### ISSUE TITLE
Wrong import in UNet Tutorial?

### ISSUE THREAD

**Issue by manuelhaussmann** [inferno-pytorch/inferno#149]
https://github.com/inferno-pytorch/inferno/blob/5493e9e38f8e3ccc7dd6aee11b0ba492d1398210/examples/plot_unet_tutorial.py#L71

Am I missing something or shouldn't this import be from `inferno.extensions.model` instead?

(Btw. thanks for the Unets and the tutorial Thorsten)

**Comment by manuelhaussmann** [comment]
>  ATM I cannot check/test it if it's enough to swap layers with models.

To run the tutorial it seems to be enough at least until the custom layers section. I haven't checked yet whether that part requires further changes.

**Comment by constantinpape** [comment]
Fixed unet examples in 62edee6354cd1fd7b7aec6e4967fab4491124f0b.
