### ISSUE TITLE
Momentum is not suitable for smoothing validation score

### ISSUE THREAD

**Issue by constantinpape** [inferno-pytorch/inferno#154]
In the current implementation of validation smoothing, we use momentum.
This puts a very high importance on the first validation score.
E.g. for 3 validation scores [.75, .2, .1] the smoothed value would be something like 0.7.

I think using a sliding window with some decay would be more appropriate.

**Comment by nasimrahaman** [comment]
Solution: use smaller momentum (~ 0.1 instead of 0.9).
