### ISSUE TITLE
pytorch 1.0 multi-processing not stable

### ISSUE THREAD

**Issue by constantinpape** [inferno-pytorch/inferno#157]
It looks like the multi-processing is not really stable in pytorch 1.0 yet.
This leads to a few non-terminating tests (not an issue in 0.4.1 !).
I have disabled the 1.0 tests for now:
https://github.com/inferno-pytorch/inferno/blob/master/.travis.yml#L11

We should check  again if this works once there is a new torch release.

**Comment by nasimrahaman** [comment]
Did we not disable multiprocessing in our tests?

**Comment by constantinpape** [comment]
For some reason even some of the tests that have `num_workers=0` hang.
Also, even if I exclude all the tests that hang, there is one process that does not get killed.
I.e. the unit tests run through and all succeed, but then the process running the unit test discovery does not exit.
When I kill that process (I can reproduce this locally with torch 1.0 as well), it hangs
somewhere in torch multiprocessing, but it's hard to backtrace where the process was started from.

**Comment by nasimrahaman** [comment]
This is weird. I’m sure pytorch 1.0 multiprocessing runs as usual (we would have known by now, if not), so it has to be somewhere in the unittests. I’ll try to investigate.

**Comment by constantinpape** [comment]
Ok, to add some context / weirdness:
All these issues only occur when I start the tests via `python -m unittest discover`, not when running the tests directly with python.
The tests that hang are here:
https://github.com/inferno-pytorch/inferno/blob/master/tests/test_training/test_callbacks/test_logging/test_tensorboard.py

**Comment by constantinpape** [comment]
Oh, I just realized, these still have `num_workers=1`.
I will update that and push again, maybe this will magically solve our issues.

**Comment by constantinpape** [comment]
Still not converging, even with `num_workers=1`.
