### ISSUE TITLE
Migrate to networkx 2.x

### ISSUE THREAD

**Issue by patricio-astudillo** [inferno-pytorch/inferno#158]
https://github.com/inferno-pytorch/inferno/blob/2f51e5077173aecc2cab6facf3e1a12cd9ad462a/inferno/extensions/containers/graph.py#L389

This line crashes with networkx version 2.2

**Comment by patricio-astudillo** [comment]
and this is the fix:

for edge in list(graph.edges(data=True)):
            source, target, _ = edge
            if 'payload' in graph[source][target]:
                del graph[source][target]['payload']

**Comment by constantinpape** [comment]
Cool!
Could you make a PR with the fixes?

**Comment by constantinpape** [comment]
I went ahead and made the PR:
https://github.com/inferno-pytorch/inferno/pull/159
