### ISSUE TITLE
Store version information only once

### ISSUE THREAD

**Issue by constantinpape** [inferno-pytorch/inferno#163]
Right now the version information is present in two different files:

https://github.com/inferno-pytorch/inferno/blob/master/setup.py#L41
https://github.com/inferno-pytorch/inferno/blob/master/inferno/__init__.py#L14

Would be better to store this in a single place. I am not sure about the best practices though.

**Comment by DerThorsten** [comment]
I would propose to use a file like `_version.py` or simmilar which contains the version info
```__version__ = '0.3.1'``` shuch that other files can import the version from `_version.py`

Also there is https://github.com/peritus/bumpversion to update multiple version strings at once (not saying we should have multiples)
