### ISSUE TITLE
conda forge downgrades pytorch to <=1.2

### ISSUE THREAD

**Issue by DerThorsten** [inferno-pytorch/inferno#196]
@constantinpape  @nasimrahaman  Is there a reason we pin `pytorch <= 1.2` in the conda recipe (https://github.com/conda-forge/inferno-feedstock/blob/5f30bedef943ee2b2c831315adb387b634a6dc90/recipe/meta.yaml#L32)
This is a bit annoying for user who want to use pytorch 1.3

**Comment by constantinpape** [comment]
This is fixed in the new release.
