### ISSUE TITLE
Combine Zip and Concatenate dataset

### ISSUE THREAD

**Issue by erjel** [inferno-pytorch/inferno#208]
Hi,

I would like to use your code base to train affinity networks for the [mutex-watershed algorithm](https://github.com/hci-unihd/mutex-watershed/tree/master/experiments/training). Unfortunately I do not have one big annotated volume but rather multiple smaller once which I need to combine into a single `RawVolume` & `SegmentationVolume` such that I can create the `Zip` based dataset.

As far as I understand there is the option to use the `Concatenate` class to combine multiple datasets into one. In the in-line documentation, however, there is the comment that `Concatenate` does not implement synchronization primitives, which would be needed for the Zip class, right?

Before I start to implement a custom version of the `HDF5VolumeLoader` I would like to ask whether my idea is too complicated and someone can point me to an easier (or already existing) solution.

Best wishes,
Eric

**Comment by constantinpape** [comment]
I think using `Concatenate` should work for your use-case if you concatenate on the outermost level.
So something like this:
```python
# implement your datasets
...
# concatenate the datasets
ds = Concatenate(*datasets)
```

**Comment by erjel** [comment]
Thanks, with your suggestion I was able to start a training session based on my dataset.
