### ISSUE TITLE
Neuroglancer integration in tensorboard logger.

### ISSUE THREAD

**Issue by constantinpape** [inferno-pytorch/inferno#32]
It would be great to have the neuroglancer viewer availble for 3D volumetric data during inference.
This would make data inspection much easier especially for data with multiple channels.

**Comment by nasimrahaman** [comment]
What I could imagine being a bit more realistic is something along the lines of a `NeuroglancerLogger` if we have a volumetric inference engine going. However, I think it's imperative we have the inference running asynchronously on a different worker, or even a different machine. Lucky for us, torch distributed provides handy primitives (see e.g. [distributed data-parallel](https://github.com/pytorch/pytorch/blob/master/torch/nn/parallel/distributed.py#L23)) for pushing tensors around over the network (or [`torch.multiprocessing`](http://pytorch.org/docs/master/multiprocessing.html) for juggling tensors between processes).

**Comment by constantinpape** [comment]
Sounds good. I guess it is not really important to have it in tensorboard, just to have some way of visualizing the volume data during inference would be helpful.

**Comment by nasimrahaman** [comment]
There are other better packages that get the job done.
