### ISSUE TITLE
Better support for Tensorboard

### ISSUE THREAD

**Issue by nasimrahaman** [inferno-pytorch/inferno#45]
[This project](https://github.com/lanpa/tensorboard-pytorch) looks like a good replacement for the manual tensorboard business we currently have going. It makes it much easier to integrate histograms, distributions, and even audio.

**Comment by nasimrahaman** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Better Tensorboard](https://trello.com/c/5OfF8lsk/10-better-tensorboard)

**Comment by constantinpape** [comment]
We are using tensorboardx already and https://github.com/imagirom/firelight is compatible with inferno and provides a nice tensorboard expansion.
