### ISSUE TITLE
Potential Collaboration

### ISSUE THREAD

**Issue by achaiah** [inferno-pytorch/inferno#50]
### Description

You guys seem to be doing something very similar to the [torchsample](https://github.com/ncullen93/torchsample) project and it seems to me that there's a ton of room for collaboration / code merging. Please consider at least pulling in some of the functionality from that library.  Also, I really like the way the callbacks are structured in torchsample.  I didn't see anything similar in inferno but I think it would be a good idea.

Thanks

**Comment by nasimrahaman** [comment]
Hi @achaiah, thanks for the pointer. Given the fact that the documentation is still a work-in-progress, I'd like to point out that inferno has it's [own callback API](https://github.com/nasimrahaman/inferno/blob/master/inferno/trainers/callbacks/base.py#L124). [Here's a short primer](http://inferno-pytorch.readthedocs.io/en/latest/usage.html#setting-up-callbacks) on building and deploying callbacks with inferno.
