### ISSUE TITLE
github badges/shields seem to be down.

### ISSUE THREAD

**Issue by DerThorsten** [inferno-pytorch/inferno#86]
badges/shields  seem to be down / 'gray'
I guess travis, readthedocs and other urls needs to be updated due to repo ownership transfer.

**Comment by nasimrahaman** [comment]
Readthedocs appears to be working, it's just travis. I've updated the badge in the super-dev branch, maybe I could manage a to test most of the things and merge to `dev`.

**Comment by DerThorsten** [comment]
the badge still says the doc is failing

**Comment by nasimrahaman** [comment]
Dr @DerThorsten, what do we do now, since the docs are no longer built by readthedocs? Get rid of the batch?

**Comment by DerThorsten** [comment]
yes, and again, someone with a gpu should build new docs and host them as discussed

**Comment by constantinpape** [comment]
This is fixed, docs are a separate issue discussed in #139
