### ISSUE TITLE
Print training / validation accuracies

### ISSUE THREAD

**Issue by inJeans** [inferno-pytorch/inferno#95]
Hey team. I was just wondering what the best way to get the trainer to print training accuracies to the console was? Thanks

**Comment by inJeans** [comment]
So I guess it is just through the use of the callback functions? There is no automatic printing to the console?

**Comment by manuelhaussmann** [comment]
Yes, currently the monitoring is all done via the tensorboard interface. And you are right, callbacks are the right way to go. If you want to have a (very preliminary) example of what that could look like you can have a look at #71 (which also introduces a progressbar and silences the trainer output completely).

**Comment by inJeans** [comment]
Oh nice 👍🏽. Thanks for that.
